#!/bin/sh
# postrm script for sleepi2-utils
#
# see: dh_installdeb(1)

set -e

if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper unmask hwclock-save.service >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper unmask hwclock-save.service >/dev/null || true
	fi
fi

#DEBHELPER#

exit 0
