#!/bin/sh
# postinst script for sleepi2-utils
#
# see: dh_installdeb(1)

set -e

if [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi

if [ -x "/usr/bin/deb-systemd-helper" ]; then
	deb-systemd-helper mask hwclock-save.service >/dev/null || true
fi

#DEBHELPER#

exit 0
